
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivbjofjsmhnatmzixqco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2YmpvZmpzbWhuYXRteml4cWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxNjgwNDIsImV4cCI6MjA1Nzc0NDA0Mn0.vW7uUXyXRIRLB6HAm_lKcV-ACx7OWiGObiHgktb9fYs";

// Set up the rewrite for the webhook endpoint
if (typeof window !== "undefined") {
  // Only run in browser environment
  const { pathname } = window.location;
  if (pathname.startsWith("/api/webhook/")) {
    // This will be handled by the edge function
    const token = pathname.split("/").pop();
    window.history.replaceState(
      {},
      document.title,
      `/settings?tab=webhooks`
    );
  }
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";
export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
