
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import "https://deno.land/x/xhr@0.1.0/mod.ts";

const CLAUDE_API_KEY = Deno.env.get('CLAUDE_API_KEY');
const CLAUDE_API_URL = "https://api.anthropic.com/v1/messages";

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
};

serve(async (req) => {
  // Handle CORS preflight requests
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders });
  }

  try {
    if (!CLAUDE_API_KEY) {
      throw new Error('CLAUDE_API_KEY is not set');
    }

    const requestData = await req.json();
    const { prompt, contentType, idea, task } = requestData;

    if (!prompt) {
      return new Response(
        JSON.stringify({ error: "Missing required field: prompt is required" }),
        { status: 400, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
      );
    }

    let logMessage = 'Generating content with Claude';
    
    // Log different message based on task type
    if (task === 'writing_style_preview') {
      logMessage = `Generating ${contentType || 'writing style'} preview with Claude`;
    } else if (contentType && idea) {
      logMessage = `Generating ${contentType} content with Claude for idea: ${idea?.title || 'Untitled'}`;
    }
    
    console.log(logMessage);
    
    // Choose the appropriate Claude model based on content complexity
    const model = "claude-3-sonnet-20240229"; // Using Sonnet for high quality content generation
    
    // Make request to Claude API
    const response = await fetch(CLAUDE_API_URL, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'x-api-key': CLAUDE_API_KEY,
        'anthropic-version': '2023-06-01'
      },
      body: JSON.stringify({
        model: model,
        max_tokens: 4000,
        temperature: 0.7, // Slightly more creative but still focused
        messages: [
          {
            role: "user",
            content: prompt
          }
        ]
      })
    });

    const data = await response.json();
    
    if (!response.ok) {
      console.error('Claude API error:', data);
      throw new Error(`Claude API error: ${data.error?.message || 'Unknown error'}`);
    }

    const generatedContent = data.content && data.content[0]?.text;

    if (!generatedContent) {
      throw new Error('No content generated by Claude');
    }

    return new Response(
      JSON.stringify({ content: generatedContent }),
      { headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  } catch (error) {
    console.error('Error in generate-with-claude function:', error);
    return new Response(
      JSON.stringify({ error: error.message || 'Unknown error' }),
      { status: 500, headers: { ...corsHeaders, 'Content-Type': 'application/json' } }
    );
  }
});
